name: delete branch on close pr
on: 
  pull_request:
    types: closed
    branches: master
  
jobs:
  clean:
    uses: super-info/cicd-reusable/.github/workflows/delete-merged-config.yml@main
    secrets: inherit  
